[build]
  command = "pnpm install && pnpm build:client"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/login"
  to = "http://168.144.122.72/prod/CPLogin/CMMTN"
  status = 200
  force = true

[[redirects]]
  from = "/api/unsub"
  to = "http://168.144.122.72/prod/CMMTN/unsub"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
