server {
    server_name oncook.co www.oncook.co;
    root /var/www/vasnumero/oncook/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/login {
        proxy_pass http://168.144.122.72/prod/CPLogin/CMMTN$is_args$args;
        proxy_set_header Host 168.144.122.72;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        add_header Access-Control-Allow-Origin *;
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/oncook.co/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/oncook.co/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 80;
    server_name oncook.co www.oncook.co;
    return 301 https://$host$request_uri;
}
